### ISSUE TITLE
Feature:  Install in local as user

### ISSUE THREAD

**Issue by sosie-js** [gvvaughan/luke#5]
Hello,

I just want to do a local install as user, it seems it is only to install system wide requiring rights
when I trigger build-aux/luke lukefile install all with a lukefile
```
package  = 'peagisub'
version  = '$USER'

defines  = {
   PACKAGE           = '"$package"',
   VERSION           = '"$version"',
   NDEBUG            = 1,
   _FORTIFY_SOURCE   = 2,
}

modules  = {
   ['peagisub']         = 'src/peagisub.lua',
}
```

it does a copy to /usr/local/share/lua/5.1/

luarocks-admin indicates in my case:
```
   Rocks trees in use:
      /home/pi/.luarocks  <--- I want here the instal or a user choosen one
      /usr/local
```

is this configurable?

EDIT: no as PREFIX seems tobe hardcoded in lib/luke/environment.lua

I mean a thing like, would be cool:
PREFIX="/home/pi/.luarocks" ./build-aux/luke lukefile install all
or better grab PREFIXES from luarocks-admin script

**Comment by sosie-js** [comment]
Solved , see the patch https://github.com/gvvaughan/luke/pull/6

**Comment by gvvaughan** [comment]
Hi @sosie-js.  Thanks for the report, and for your PR#6.

You can already pass a value for PREFIX as an argument to the `luke` command line invocation.  This is typically how I integrate a `luke`-based build into a rockspec.  For example, see https://github.com/gvvaughan/lyaml/blob/master/lyaml-git-1.rockspec#L30-L33

If you are calling `luke` directly from the shell, or make or similar, then you would:

```bash
build-aux/luke "PREFIX=$HOME/.luarocks" all install
```

If you know in advance that you really want to defer to the environment, then you can invoke as:


```bash
build-aux/luke "PREFIX=${PREFIX-/some/default/incase/PREFIX/is/not/set!}" all install
```

note: no need for leading `./` - when running a command in a subdirectory the command PATH is not searched
note 2: no need to name `lukefile` since that's the default

HTH!  Please close this issue and PR#6 if that resolves your problem, otherwise do add any additional questions here or in the PR.

**Comment by sosie-js** [comment]
Thank you very much @gvvaughan  for your answer, I cannot guess you can pass PREFIX as a parameter. 
I wanted to reuse the configuration of luarock so I've patched your rock seeing your answer lately.

In fact your script works with the latest luarocks, as the ubuntu/debian is outdated  either
```shell
#install latest luarock locally
sudo apt install luarocks
luarocks install --local luarocks
sudo apt purge luarocks
```

or it has to be changed to
```lua
#! /bin/sh

# Wrapper luke-luarocks                                                                                     
# Big thanks to Gary Vaughan for this                                                                       
# see https://github.com/gvvaughan/luke/pull/6                                                              


case $1 in
    --local) shift; key=1 ;;
    --global) shift; key=2 ;;
esac

test -z "$key" || {
    prefix=$(lua -e "$(luarocks config)" -e "for k, v in next,rocks_trees do  if k == $key then print(v) end end")
    set -- PREFIX=${PREFIX-"$prefix"} ${1+"$@"}
}

exec build-aux/build-aux/luke ${1+"$@"}
```

Yours rocksfully ,
                               SoSie

**Comment by sosie-js** [comment]
in fact the script depend on what is set on your config file for rocktrees: string or table. Mine is for string yours is for table
to force to use yours a file config.lua , config-5.1.lua, .. with this need to be created in /etc/luarocks or in ~/.luarocks
```lua
--https://github.com/luarocks/luarocks/wiki/Config-file-format
rocks_trees = {
   {
       name= "user",
       root = home..[[/.luarocks]],
       bin_dir = home.."/.local/bin",
       lib_dir = home.."/.luarocks/lib/lua/5.1", 
       lua_dir = home.."/.luarocks/share/lua/5.1
   },
   {  
       name="system",
       root = [[/usr/local]],
       bin_dir = [["/usr/local/bin"]],
       lib_dir = [["/usr/local/lib/lua/5.1"]], 
       lua_dir = [["/usr/local/share/lua/5.1]]
   },
}
``
